env:
  node: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: "detect"
plugins:
  - "@typescript-eslint"
  - "react"
rules:
  "react/prop-types": "off"
  "react/react-in-jsx-scope": "off"